export const projectData = [
    {
      image: ['/work/3.png', '/work/1.png','/work/2.png','/work/4.png',],
      category: 'fullstack',
      name: 'Rukun Perkasa Ecommerce',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore velit vitae odio? Adipisci aspernatur sint debitis voluptatum neque blanditiis. Sint quod, inventore excepturi fuga quidem aliquam totam dolorem quibusdam ex quo cum temporibus non ad libero quasi suscipit at blanditiis eveniet? Voluptas ab porro dolorem vero, delectus aperiam error est architecto voluptatum earum pariatur et. Reiciendis harum adipisci exercitationem asperiores ut, molestiae aperiam vitae expedita sint id quam voluptates possimus voluptatem illum, reprehenderit libero quo consectetur, quod repellendus laborum labore aut ipsa ad non. Accusamus obcaecati nulla blanditiis itaque debitis, laborum neque eaque possimus reiciendis ipsam a iure, at perferendis?',
      link: '/',
      github: '/',
    },
    {
      image: ['/work/1.png', '/work/3.png'],
      category: 'react js',
      name: 'Recycle Waste Wisely',
      description: 'This website is the final project of the Certified Internship and Independent Study at Orbit Future Academy Batch 5. The project is specifically designed for an automated waste classification website. It is built using React Vite for the frontend, Tailwind CSS for styling, and TensorFlow.js for loading data from the model.',
      link: 'https://rewwis.vercel.app/',
      github: 'https://github.com/chndrwali/RecycleWasteWisely',
    },
    {
      image: ['/work/2.png', '/work/1.png'],
      category: 'react js',
      name: 'TogetherBoost App',
      description: 'This website is the final project of the Certified Internship and Independent Study at Dicoding Indonesia Cycle 4. The project revolves around the theme of "Inclusivity in Education" and is built using React Vite for the frontend, Tailwind CSS as the styling framework, Express.js for the backend, and also incorporates the Redux library.',
      link: 'https://togetherboost.vercel.app/',
      github: 'https://github.com/chndrwali/capstone-fe',
    },
    {
      image: ['/work/4.png', '/work/1.png'],
      category: 'react js',
      name: 'Twitwar Forum',
      description: 'As a final submission for the "Becoming a React Web Developer Expert" class, this website is constructed using React Vite, Tailwind CSS, and Redux. It effectively harnesses APIs provided by Dicoding Indonesia, showcasing the skills acquired throughout the course.',
      link: 'https://twitwar-forum.vercel.app/',
      github: 'https://github.com/chndrwali/twitwar-forum',
    },
    {
      image: ['/work/4.png', '/work/1.png'],
      category: 'react js',
      name: 'Masked Apps',
      description: 'This website is created to fulfill the needs of the final semester exam for the Sistem Pakar course at National Pasim University. Creted using Vite, Tailwind CSS, and TensorFlowJS, we emphasize responsiveness, aesthetic design, and code quality. Tailwind CSS provides an intuitive interface, and Eslint guarantees high-quality code.',
      link: 'https://maskedapp.vercel.app/',
      github: 'https://github.com/chndrwali/MaskedApps',
    },
    {
      image: ['/work/4.png', '/work/1.png'],
      category: 'react js',
      name: 'Twitwar Forum',
      description: 'As a final submission for the "Becoming a React Web Developer Expert" class, this website is constructed using React Vite, Tailwind CSS, and Redux. It effectively harnesses APIs provided by Dicoding Indonesia, showcasing the skills acquired throughout the course.',
      link: 'https://twitwar-forum.vercel.app/',
      github: 'https://github.com/chndrwali/twitwar-forum',
    },
  ];