export const projectData = [
    {
      image: ['/work/3.png', '/work/1.png','/work/2.png','/work/4.png',],
      category: 'fullstack',
      name: 'Rukun Perkasa',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore velit vitae odio? Adipisci aspernatur sint debitis voluptatum neque blanditiis. Sint quod, inventore excepturi fuga quidem aliquam totam dolorem quibusdam ex quo cum temporibus non ad libero quasi suscipit at blanditiis eveniet? Voluptas ab porro dolorem vero, delectus aperiam error est architecto voluptatum earum pariatur et. Reiciendis harum adipisci exercitationem asperiores ut, molestiae aperiam vitae expedita sint id quam voluptates possimus voluptatem illum, reprehenderit libero quo consectetur, quod repellendus laborum labore aut ipsa ad non. Accusamus obcaecati nulla blanditiis itaque debitis, laborum neque eaque possimus reiciendis ipsam a iure, at perferendis?',
      link: '/',
      github: '/',
    },
    {
      image: ['/work/rewwis.webp'],
      category: 'react js',
      name: 'Recycle Waste Wisely',
      description: 'This website is the final project of the Certified Internship and Independent Study at Orbit Future Academy Batch 5. The project is specifically designed for an automated waste classification website. It is built using React Vite for the frontend, Tailwind CSS for styling, and TensorFlow.js for loading data from the model.',
      link: 'https://rewwis.vercel.app/',
      github: 'https://github.com/chndrwali/RecycleWasteWisely',
    },
    {
      image: ['/work/togetherboost.webp'],
      category: 'react js',
      name: 'TogetherBoost App',
      description: 'This website is the final project of the Certified Internship and Independent Study at Dicoding Indonesia Cycle 4. The project revolves around the theme of "Inclusivity in Education" and is built using React Vite for the frontend, Tailwind CSS as the styling framework, Express.js for the backend, and also incorporates the Redux library.',
      link: 'https://togetherboost.vercel.app/',
      github: 'https://github.com/chndrwali/capstone-fe',
    },
    {
      image: ['/work/twitwar.webp'],
      category: 'react js',
      name: 'Twitwar Forum',
      description: 'As a final submission for the "Becoming a React Web Developer Expert" class, this website is constructed using React Vite, Tailwind CSS, and Redux. It effectively harnesses APIs provided by Dicoding Indonesia, showcasing the skills acquired throughout the course.',
      link: 'https://twitwar-forum.vercel.app/',
      github: 'https://github.com/chndrwali/twitwar-forum',
    },
    {
      image: ['/work/maskedapp.webp'],
      category: 'submission',
      name: 'Masked Apps',
      description: 'This website is created to fulfill the needs of the final semester exam for the Sistem Pakar course at National Pasim University. Creted using Vite, Tailwind CSS, and TensorFlowJS, we emphasize responsiveness, aesthetic design, and code quality. Tailwind CSS provides an intuitive interface, and Eslint guarantees high-quality code.',
      link: 'https://maskedapp.vercel.app/',
      github: 'https://github.com/chndrwali/MaskedApps',
    },
    {
      image: ['/work/SrymStore.webp'],
      category: 'submission',
      name: 'Srym Store',
      description: 'This website is created to fulfill the needs of the final semester exam for the E-Commerce course at National Pasim University. Utilizing Progressive Web Apps, Tailwind CSS, and Eslint, we emphasize responsiveness, aesthetic design, and code quality. Progressive Web Apps ensure easy access, Tailwind CSS provides an intuitive interface, and Eslint guarantees high-quality code.',
      link: 'https://srymecommerce.netlify.app/',
      github: 'https://github.com/chndrwali/WebEcommerce',
    },
    {
      image: ['/work/4.png', '/work/1.png'],
      category: 'submission',
      name: 'Candra Food',
      description: 'As a final submission for the "Becoming a React Web Developer Expert" class, this website is constructed using React Vite, Tailwind CSS, and Redux. It effectively harnesses APIs provided by Dicoding Indonesia, showcasing the skills acquired throughout the course.',
      link: 'https://candrafood-pwa.vercel.app/',
      github: 'https://github.com/chndrwali/restaurant-catalogueWPA',
    },
    {
      image: ['/work/klasifikasidicoding.webp'],
      category: 'submission',
      name: 'Submission Dicoding',
      description: 'Successfully trained a dataset of images with 6 classes, achieving an accuracy of 95%, and a validation accuracy of 85%.',
      link: 'https://candrafood-pwa.vercel.app/',
      github: 'https://github.com/chndrwali/Submission-ML-3-ImageClassification-Deployment',
    },
    {
      image: ['/work/klasifikasiorbit.webp'],
      category: 'submission',
      name: 'Model Image Classification 12 Classes',
      description: 'Successfully trained a dataset with 12 classes using the MobileNetV2 architecture and converted it into a TensorFlow.js model with an accuracy of 97%.',
      link: '/projects',
      github: 'https://github.com/chndrwali/model-klasifikasi-orbit',
    },
    {
      image: ['/work/dicodingkelulusan.webp'],
      category: 'certificates',
      name: 'Sertifikat Kelulusan Dicoding',
      description: 'Successfully completed the Front-End Web and Back-End Training in the Dicoding X Kampus Merdeka Angkatan 3 SIB Program.',
      link: 'https://www.linkedin.com/in/chndrwali/details/certifications/1635541981815/single-media-viewer/?profileId=ACoAADVInc4B_JHLHqbVHb8NC7oF3-SuA6Oom8k',
      github: 'https://github.com/chndrwali',
    },
    {
      image: ['/work/alibabasertifikat.webp'],
      category: 'certificates',
      name: 'Certified Developer Alibaba Cloud',
      description: 'Successfully registered as a DevHandal participant and completed the class on creating a blog on the Alibaba-owned AWS Cloud platform.',
      link: 'https://www.linkedin.com/in/chndrwali/details/certifications/1635548464440/single-media-viewer/?profileId=ACoAADVInc4B_JHLHqbVHb8NC7oF3-SuA6Oom8k',
      github: 'https://github.com/chndrwali',
    },
    {
      image: ['/work/frontendexpert.webp'],
      category: 'certificates',
      name: 'Menjadi Front End Web Developer Expert',
      description: 'Successfully trained three datasets, namely text classification, time series, and image classification, using Google Colab and several machine learning libraries.',
      link: 'https://www.dicoding.com/certificates/72ZD8YVQ9ZYW',
      github: 'https://github.com/chndrwali',
    },
    {
      image: ['/work/reactexpert.webp'],
      category: 'certificates',
      name: 'Menjadi React Web Developer Expert',
      description: 'Successfully trained three datasets, namely text classification, time series, and image classification, using Google Colab and several machine learning libraries.',
      link: 'https://www.dicoding.com/certificates/MRZMQRYJLPYQ',
      github: 'https://github.com/chndrwali',
    },
    {
      image: ['/work/machinelearning.webp'],
      category: 'certificates',
      name: 'Belajar Pengembangan Machine Learning',
      description: 'Successfully trained three datasets, namely text classification, time series, and image classification, using Google Colab and several machine learning libraries.',
      link: 'https://www.dicoding.com/certificates/L4PQQ456VPO1',
      github: 'https://github.com/chndrwali',
    },
  ];